-- =========================================
-- TABLA: USUARIOS
-- =========================================

CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    rol VARCHAR2(30),
    estado VARCHAR2(20)
);

-- =========================================
-- TABLA: AUTOBUSES
-- =========================================

CREATE TABLE autobuses (
    id_autobus NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR2(20) UNIQUE NOT NULL,
    modelo VARCHAR2(50),
    capacidad NUMBER NOT NULL,
    estado VARCHAR2(30)
);

-- =========================================
-- TABLA: PILOTOS
-- =========================================

CREATE TABLE pilotos (
    id_piloto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    dpi VARCHAR2(20) UNIQUE,
    telefono VARCHAR2(20),
    licencia VARCHAR2(30),
    estado VARCHAR2(20)
);

-- =========================================
-- TABLA: RUTAS
-- =========================================

CREATE TABLE rutas (
    id_ruta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origen VARCHAR2(100),
    destino VARCHAR2(100),
    distancia_km NUMBER,
    precio_base NUMBER(10,2),
    duracion VARCHAR2(30)
);

-- =========================================
-- TABLA: PASAJEROS
-- =========================================

CREATE TABLE pasajeros (
    id_pasajero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    dpi VARCHAR2(20),
    telefono VARCHAR2(20),
    correo VARCHAR2(100)
);

-- =========================================
-- TABLA: CLIENTES_ENCOMIENDA
-- =========================================

CREATE TABLE clientes_encomienda (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    telefono VARCHAR2(20),
    direccion VARCHAR2(200),
    dpi VARCHAR2(20)
);

-- =========================================
-- TABLA: VIAJES
-- =========================================

CREATE TABLE viajes (
    id_viaje NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_ruta NUMBER NOT NULL,
    id_autobus NUMBER NOT NULL,
    id_piloto NUMBER NOT NULL,

    fecha_salida DATE,
    hora_salida VARCHAR2(10),
    estado VARCHAR2(30),

    CONSTRAINT fk_viaje_ruta
        FOREIGN KEY (id_ruta)
        REFERENCES rutas(id_ruta),

    CONSTRAINT fk_viaje_autobus
        FOREIGN KEY (id_autobus)
        REFERENCES autobuses(id_autobus),

    CONSTRAINT fk_viaje_piloto
        FOREIGN KEY (id_piloto)
        REFERENCES pilotos(id_piloto)
);

-- =========================================
-- TABLA: BOLETOS
-- =========================================

CREATE TABLE boletos (
    id_boleto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_pasajero NUMBER NOT NULL,
    id_viaje NUMBER NOT NULL,

    numero_asiento NUMBER NOT NULL,
    fecha_compra DATE DEFAULT SYSDATE,
    precio NUMBER(10,2),
    estado VARCHAR2(20),

    CONSTRAINT fk_boleto_pasajero
        FOREIGN KEY (id_pasajero)
        REFERENCES pasajeros(id_pasajero),

    CONSTRAINT fk_boleto_viaje
        FOREIGN KEY (id_viaje)
        REFERENCES viajes(id_viaje)
);

-- =========================================
-- TABLA: ENCOMIENDAS
-- =========================================

CREATE TABLE encomiendas (
    id_encomienda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_remitente NUMBER NOT NULL,
    id_destinatario NUMBER NOT NULL,
    id_viaje NUMBER NOT NULL,

    peso NUMBER(10,2),
    descripcion VARCHAR2(200),
    costo NUMBER(10,2),

    codigo_rastreo VARCHAR2(50),
    estado VARCHAR2(30),

    fecha_envio DATE DEFAULT SYSDATE,

    CONSTRAINT fk_encomienda_remitente
        FOREIGN KEY (id_remitente)
        REFERENCES clientes_encomienda(id_cliente),

    CONSTRAINT fk_encomienda_destinatario
        FOREIGN KEY (id_destinatario)
        REFERENCES clientes_encomienda(id_cliente),

    CONSTRAINT fk_encomienda_viaje
        FOREIGN KEY (id_viaje)
        REFERENCES viajes(id_viaje)
);

-- =========================================
-- TABLA: MANTENIMIENTOS
-- =========================================

CREATE TABLE mantenimientos (
    id_mantenimiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_autobus NUMBER NOT NULL,

    fecha DATE,
    descripcion VARCHAR2(200),
    costo NUMBER(10,2),
    tipo VARCHAR2(50),

    CONSTRAINT fk_mantenimiento_autobus
        FOREIGN KEY (id_autobus)
        REFERENCES autobuses(id_autobus)
);

-- =========================================
-- TABLA: AUDITORIA
-- =========================================

CREATE TABLE auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tabla_afectada VARCHAR2(50),
    accion VARCHAR2(20),
    usuario_sistema VARCHAR2(100),
    fecha_accion DATE DEFAULT SYSDATE,
    descripcion VARCHAR2(200)
);

-- ============================================================
-- MEJORAS
-- ============================================================

-- Evita la sobreventa de un mismo asiento dentro del mismo viaje.
ALTER TABLE boletos
ADD CONSTRAINT uq_asiento_viaje
UNIQUE (id_viaje, numero_asiento);

-- campo para cerrar viajes y medir duracion
-- NULL mientras no haya finalizado o iniciado
ALTER TABLE viajes
ADD (
    fecha_fin DATE
);

ALTER TABLE viajes
ADD CONSTRAINT ck_viaje_fechas
CHECK (fecha_fin IS NULL OR fecha_salida IS NULL OR fecha_fin >= fecha_salida);

--para que el codigo de rastreo sea unico
ALTER TABLE encomiendas
ADD CONSTRAINT uq_encomienda_codigo
UNIQUE (codigo_rastreo);